resources:
  my-example-bucket-testmb-22:
    resource_id: my-example-bucket-testmb-22
    technical_id: null
    resource_type: S3
metadata:
  version: '1.0'
  last_sync: '2026-02-15T03:12:46.862495'
