resources:
  hello-role:
    type: iam_role
    tech_id: arn:aws:iam::745243048623:role/aa-simple-hallo-welt-lambda-role-rename
  hello-lambda:
    type: lambda
    tech_id: arn:aws:lambda:eu-central-1:745243048623:function:aa-hallo-welt
deployment_progress: null
