resources:
  my-bucket:
    type: s3
    tech_id: arn:aws:s3:::my-example-testmb-bucket-22
  website:
    type: s3_deploy
    tech_id: s3://my-example-testmb-bucket-22
  cloud-front:
    type: cloudfront
    tech_id: arn:aws:cloudfront::E10FO9LNPYAVXS
