resources:
  cloudfront:
    type: cloudfront
    tech_id: arn:aws:cloudfront::745243048623:distribution/E4PYL7N4QM15Z
  my-bucket:
    type: s3
    tech_id: arn:aws:s3:::my-example-testmb-bucket-22
  website:
    type: s3_deploy
    tech_id: s3://my-example-testmb-bucket-22
  lambda-role:
    type: iam_role
    tech_id: arn:aws:iam::745243048623:role/hallo-welt-lambda-role
  lambda:
    type: lambda
    tech_id: arn:aws:lambda:eu-central-1:745243048623:function:hallo-welt
  api-gateway:
    type: api_gateway
    tech_id: https://uvjfr5s7d6.execute-api.eu-central-1.amazonaws.com
